version: '3.8'

services:
#  redis:
#    image: redis:latest
#    container_name: my-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - my-network

  backend:
    image: vietduc39779/my-backend:latest
    container_name: my_backend
    ports:
      - "8080:8080"
#    depends_on:
#      - redis
    networks:
      - my-network
#    environment:
#      # Nếu bạn muốn truyền thông qua biến môi trường (tùy chọn)
#      # Cách này sẽ GHI ĐÈ giá trị trong application.yml nếu có
#      - SPRING_REDIS_HOST=turntable.proxy.rlwy.net
#      - SPRING_REDIS_PORT=58723
#      - SPRING_REDIS_PASSWORD=PvAmWOLwVfzBEqQjiKBxmauFbpzOVdCo
#      - SPRING_REDIS_SSL=true
#      # Hoặc nếu dùng spring.redis.username:
#      - SPRING_REDIS_USERNAME=default

networks:
  my-network:
    driver: bridge
