version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  backend:
    image: vietduc39779/my-backend:latest
    container_name: my_backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my-network
    environment:
      - SPRING_DATA_REDIS_HOST=my-redis
      - SPRING_DATA_REDIS_PORT=6379

networks:
  my-network:
    driver: bridge
