NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_YWxsb3dpbmctY3ViLTU1LmNsZXJrLmFjY291bnRzLmRldiQ"
CLERK_SECRET_KEY: "sk_test_l07VMBsLaiQOMbNRFGrPSgstg2g20wUTrpwDST4ASM"
clerk:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsvAZJARYPJ6MGN8Kyw4u
    YlB0fdxExRt1mWxmsw2YoPBNDYMENen2P9ZcAmILnUkNCD0gomomfMjWWBjhGJrO
    CxdZVsTLBhyM4BCEzpdhDtXD/QkCHNZu8ayCF8rYenNYPa8OeI4CcbKxVxVopmam
    vh86MyE+/+JJbed+/UTabif27Fm8tGy5a+moopmLXJo8Wyu9Fd+PWVWZ3cTYpmQF
    FIiXGNgkOFHiUXYPAgI+2ZC8l7ivh/SJNa0o9mp7PA0YGH8E8z1KhydElqqPtKH2
    5YKwPNpnW7Kg9Xyi1ykU863nmFgea56fEVmRkztOju/WpGqhSTVMaxgQtuxHSMSv
    SwIDAQAB
    -----END PUBLIC KEY-----



spring:
  redis:
    ssl: false
    timeout: 5s
  datasource:
    url: "jdbc:postgresql://ep-autumn-block-a1n9tyd9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
    username: "neondb_owner"
    password: "npg_lrsR5WUt7LEM"
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:postgresql://192.168.100.102:5432/mydb
#    username: myuser
#    password: mypassword
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    caffeine:
      spec: maximumSize=20,expireAfterAccess=30m,recordStats

server:
  port: 8080
  servlet:
    context-path: /demo

springdoc:
  api-docs:
    version: OPENAPI_3_0
  api-path: /demo/api-docs

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    
vnpay:
  tmnCode: C8APZ1UO
  hashSecret: GONRPHP7A9ZAUFXZUOM809Z2O3938AYR
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/demo/return_url
