spring:
  datasource:
    url: "jdbc:postgresql://ep-autumn-block-a1n9tyd9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
    username: "neondb_owner"
    password: "npg_lrsR5WUt7LEM"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /demo

springdoc:
  api-docs:
    version: OPENAPI_3_0
  api-path: /demo/api-docs